name: 🚀 Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main  # Déploie à chaque push sur main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout le code
        uses: actions/checkout@v4

      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installe les dépendances
        run: npm install

      - name: Build du projet
        run: npm run build

      - name: Upload du dossier dist
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Déploie sur GitHub Pages
        uses: actions/deploy-pages@v1
